#!/usr/bin/env python3
"""
Enhanced Contract models with AI generation, versioning, and JSON placeholders
"""

from sqlalchemy import Column, String, Boolean, Text, JSON, ForeignKey, Integer, Enum, DateTime, Numeric, Date, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum
import uuid
from .base import Base, TimestampMixin, SoftDeleteMixin


class ContractType(enum.Enum):
    """Type of contract"""
    MANAGED_SERVICES = "managed_services"  # MSP support contract
    SOFTWARE_LICENSE = "software_license"  # Software licensing contract
    SAAS_SUBSCRIPTION = "saas_subscription"  # SaaS subscription
    MAINTENANCE = "maintenance"  # Maintenance agreement
    SUPPORT_HOURS = "support_hours"  # Pre-paid support hours
    CONSULTING = "consulting"  # Consulting retainer
    WARRANTY = "warranty"  # Warranty coverage
    CUSTOM = "custom"  # Custom contract type


class ContractStatus(enum.Enum):
    """Status of the contract"""
    DRAFT = "draft"
    PENDING_SIGNATURE = "pending_signature"
    ACTIVE = "active"
    PENDING_RENEWAL = "pending_renewal"
    EXPIRED = "expired"
    CANCELLED = "cancelled"
    SUSPENDED = "suspended"


class ContractTemplateVersion(Base, TimestampMixin):
    """Contract template version with JSON placeholders"""
    """
    Versioned contract templates with JSON placeholders for quoting
    """
    __tablename__ = "contract_template_versions"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    template_id = Column(String(36), ForeignKey("enhanced_contract_templates.id", ondelete="CASCADE"), nullable=False, index=True)
    tenant_id = Column(String(36), ForeignKey("tenants.id"), nullable=False, index=True)
    
    # Version info
    version_number = Column(Integer, nullable=False)  # 1, 2, 3, etc.
    version_name = Column(String(100), nullable=True)  # e.g., "v2.1 - Updated SLA terms"
    is_current = Column(Boolean, default=False, nullable=False, index=True)  # Current active version
    
    # Template content with JSON placeholders
    # Placeholders format: {{placeholder_name}} or {{placeholder_name|default_value}}
    # Example: {{customer_name}}, {{monthly_fee|0}}, {{start_date|{{today}}}}
    template_content = Column(Text, nullable=False)  # Full contract template with placeholders
    
    # JSON schema for placeholders (defines what placeholders are available and their types)
    placeholder_schema = Column(JSON, nullable=True)  # {
    #   "customer_name": {"type": "string", "required": true, "description": "Customer company name"},
    #   "monthly_fee": {"type": "number", "required": true, "description": "Monthly fee in GBP"},
    #   "start_date": {"type": "date", "required": false, "default": "today"}
    # }
    
    # Default values for placeholders
    default_values = Column(JSON, nullable=True)  # {"customer_name": "", "monthly_fee": 0}
    
    # Template metadata
    description = Column(Text, nullable=True)  # What changed in this version
    created_by = Column(String(36), ForeignKey("users.id"), nullable=True)
    
    # Relationships
    template = relationship("EnhancedContractTemplate", back_populates="versions")
    tenant = relationship("Tenant")
    creator = relationship("User", foreign_keys=[created_by])
    
    def __repr__(self):
        return f"<ContractTemplateVersion {self.version_number} of template {self.template_id}>"
    
    __table_args__ = (
        Index('idx_template_version', 'template_id', 'version_number'),
        Index('idx_template_current', 'template_id', 'is_current'),
    )


class EnhancedContractTemplate(Base, TimestampMixin):
    """
    Contract templates with AI generation support and versioning
    """
    __tablename__ = "enhanced_contract_templates"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id = Column(String(36), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Template details
    name = Column(String(255), nullable=False, index=True)
    description = Column(Text, nullable=True)
    contract_type = Column(Enum(ContractType), nullable=False, index=True)
    
    # AI generation metadata
    ai_generated = Column(Boolean, default=False, nullable=False)  # Was this generated by AI?
    ai_generation_prompt = Column(Text, nullable=True)  # Prompt used to generate template
    ai_generated_at = Column(DateTime(timezone=True), nullable=True)
    ai_generated_by = Column(String(36), ForeignKey("users.id"), nullable=True)
    
    # Template status
    is_active = Column(Boolean, default=True, nullable=False, index=True)
    is_system = Column(Boolean, default=False, nullable=False)  # System template vs tenant-specific
    is_public = Column(Boolean, default=False, nullable=False)  # Can be used by other tenants (future feature)
    
    # Categories and tags for organization
    category = Column(String(100), nullable=True, index=True)  # e.g., "MSP", "Software", "Support"
    tags = Column(JSON, default=list)  # ["recurring", "monthly", "sla-required"]
    
    # Relationships
    tenant = relationship("Tenant", backref="enhanced_contract_templates")
    versions = relationship("ContractTemplateVersion", back_populates="template", order_by="ContractTemplateVersion.version_number.desc()")
    ai_generator = relationship("User", foreign_keys=[ai_generated_by])
    
    def __repr__(self):
        return f"<EnhancedContractTemplate {self.name} ({self.contract_type.value})>"
    
    __table_args__ = (
        Index('idx_template_tenant_type', 'tenant_id', 'contract_type'),
        Index('idx_template_active', 'tenant_id', 'is_active'),
    )


class Contract(Base, TimestampMixin, SoftDeleteMixin):
    """Contract generated from template"""
    """
    Contracts generated from templates with filled placeholders
    """
    __tablename__ = "contracts"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id = Column(String(36), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True)
    customer_id = Column(String(36), ForeignKey("customers.id"), nullable=False, index=True)
    template_id = Column(String(36), ForeignKey("enhanced_contract_templates.id"), nullable=True, index=True)
    template_version_id = Column(String(36), ForeignKey("contract_template_versions.id"), nullable=True, index=True)
    
    # Contract identification
    contract_number = Column(String(100), unique=True, nullable=False, index=True)
    contract_name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    
    # Contract type and status
    contract_type = Column(Enum(ContractType), nullable=False, index=True)
    status = Column(Enum(ContractStatus), default=ContractStatus.DRAFT, nullable=False, index=True)
    
    # Dates
    start_date = Column(Date, nullable=False, index=True)
    end_date = Column(Date, nullable=True, index=True)
    renewal_date = Column(Date, nullable=True, index=True)
    signed_date = Column(Date, nullable=True)
    
    # Financials
    monthly_value = Column(Numeric(12, 2), nullable=True)
    annual_value = Column(Numeric(12, 2), nullable=True)
    setup_fee = Column(Numeric(12, 2), default=0, nullable=False)
    currency = Column(String(3), default="GBP", nullable=False)
    
    # Generated contract content (with placeholders filled)
    contract_content = Column(Text, nullable=False)  # Final contract with all placeholders replaced
    
    # Placeholder values used (for reference and re-generation)
    placeholder_values = Column(JSON, nullable=True)  # {"customer_name": "Acme Corp", "monthly_fee": 500}
    
    # Contract terms and details
    terms = Column(Text, nullable=True)
    sla_level = Column(String(50), nullable=True)
    included_services = Column(JSON, nullable=True)
    excluded_services = Column(JSON, nullable=True)
    
    # Related entities
    opportunity_id = Column(String(36), ForeignKey("opportunities.id"), nullable=True, index=True)
    quote_id = Column(String(36), ForeignKey("quotes.id"), nullable=True, index=True)
    
    # Signatures and approval
    requires_signature = Column(Boolean, default=True, nullable=False)
    signed_by_customer = Column(Boolean, default=False, nullable=False)
    signed_by_company = Column(Boolean, default=False, nullable=False)
    customer_signed_at = Column(DateTime(timezone=True), nullable=True)
    company_signed_at = Column(DateTime(timezone=True), nullable=True)
    signed_by_user_id = Column(String(36), ForeignKey("users.id"), nullable=True)
    
    # Notes and metadata
    notes = Column(Text, nullable=True)
    contract_metadata = Column(JSON, nullable=True)  # Renamed from 'metadata' to avoid SQLAlchemy conflict
    
    # Relationships
    tenant = relationship("Tenant", backref="contracts")
    customer = relationship("Customer", backref="contracts")
    template = relationship("EnhancedContractTemplate", backref="contracts")
    template_version = relationship("ContractTemplateVersion", backref="contracts")
    opportunity = relationship("Opportunity", backref="contracts")
    quote = relationship("Quote", backref="contracts")
    signer = relationship("User", foreign_keys=[signed_by_user_id])
    
    def __repr__(self):
        return f"<Contract {self.contract_number} ({self.contract_type.value})>"
    
    __table_args__ = (
        Index('idx_contract_tenant_customer', 'tenant_id', 'customer_id'),
        Index('idx_contract_status_type', 'status', 'contract_type'),
        Index('idx_contract_opportunity', 'opportunity_id'),
    )

